version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine # Specifies the PostgreSQL image and version
    environment:
      POSTGRES_DB: mydatabase # Sets the database name
      POSTGRES_USER: myuser # Sets the database user
      POSTGRES_PASSWORD: mypassword # Sets the database password
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Mounts a named volume for data persistence

volumes:
  db_data: # Defines the named volume