version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: admin123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase 
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: admin123 
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data: # Defines the named volume